import type { Metadata } from 'next';
import { generalSans } from './fonts';
import './globals.css';
import Navigation from '@/ui/common/navigation/navigation';
import { GlobalContextProvider } from '@/lib/context/context-store';

export const metadata: Metadata = {
	title: 'Products',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={`${generalSans.className}`}>
				<GlobalContextProvider>
					<Navigation />
					{children}
				</GlobalContextProvider>
			</body>
		</html>
	);
}
